// Gerado a partir de ClassifSetorial.xlsx — mapa código-raiz (4 letras) → setor B3.
// Usado pelo motor do Raio-X para calcular exposição setorial da carteira.
export const SETORES_B3: Record<string, string> = {
  AALR: "Saúde",
  ABCB: "Financeiro",
  ABEV: "Consumo não Cíclico",
  ADMF: "Financeiro",
  AERI: "Bens Industriais",
  AESO: "Utilidade Pública",
  AFLT: "Utilidade Pública",
  AGRO: "Consumo não Cíclico",
  AGRU: "Bens Industriais",
  AGXY: "Consumo não Cíclico",
  AHEB: "Consumo Cíclico",
  ALLD: "Consumo Cíclico",
  ALOS: "Financeiro",
  ALPA: "Consumo Cíclico",
  ALPK: "Bens Industriais",
  ALUP: "Utilidade Pública",
  AMAR: "Consumo Cíclico",
  AMBP: "Utilidade Pública",
  AMER: "Consumo Cíclico",
  AMOB: "Consumo Cíclico",
  ANIM: "Consumo Cíclico",
  APTI: "Consumo não Cíclico",
  ARML: "Bens Industriais",
  ARND: "Financeiro",
  ASAI: "Consumo não Cíclico",
  ATED: "Consumo Cíclico",
  AUAU: "Consumo Cíclico",
  AURA: "Materiais Básicos",
  AURE: "Utilidade Pública",
  AVLL: "Consumo Cíclico",
  AXIA: "Utilidade Pública",
  AZEV: "Bens Industriais",
  AZTE: "Petróleo, Gás e Biocombustíveis",
  AZUL: "Bens Industriais",
  AZZA: "Consumo Cíclico",
  BALM: "Saúde",
  BAUH: "Consumo não Cíclico",
  BAZA: "Financeiro",
  BBAS: "Financeiro",
  BBDC: "Financeiro",
  BBML: "Bens Industriais",
  BBSE: "Financeiro",
  BDLL: "Bens Industriais",
  BEEF: "Consumo não Cíclico",
  BEES: "Financeiro",
  BETP: "Outros",
  BGIP: "Financeiro",
  BHIA: "Consumo Cíclico",
  BIED: "Consumo Cíclico",
  BIOM: "Saúde",
  BLAU: "Saúde",
  BMEB: "Financeiro",
  BMGB: "Financeiro",
  BMIN: "Financeiro",
  BMKS: "Consumo Cíclico",
  BMOB: "Tecnologia da Informação",
  BNBR: "Financeiro",
  BOBR: "Consumo não Cíclico",
  BPAC: "Financeiro",
  BPAN: "Financeiro",
  BPAR: "Financeiro",
  BRAP: "Materiais Básicos",
  BRAV: "Petróleo, Gás e Biocombustíveis",
  BRBI: "Financeiro",
  BRKM: "Materiais Básicos",
  BRQB: "Tecnologia da Informação",
  BRSR: "Financeiro",
  BRST: "Comunicações",
  BSCS: "Financeiro",
  BSLI: "Financeiro",
  CALI: "Consumo Cíclico",
  CAMB: "Consumo Cíclico",
  CAML: "Consumo não Cíclico",
  CASH: "Tecnologia da Informação",
  CASN: "Utilidade Pública",
  CATA: "Consumo Cíclico",
  CBAV: "Materiais Básicos",
  CBEE: "Utilidade Pública",
  CCTY: "Consumo Cíclico",
  CEAB: "Consumo Cíclico",
  CEBR: "Utilidade Pública",
  CEDO: "Consumo Cíclico",
  CEEB: "Utilidade Pública",
  CEED: "Utilidade Pública",
  CEGR: "Utilidade Pública",
  CGAS: "Utilidade Pública",
  CGRA: "Consumo Cíclico",
  CLSC: "Utilidade Pública",
  CMIG: "Utilidade Pública",
  CMIN: "Materiais Básicos",
  COCE: "Utilidade Pública",
  COGN: "Consumo Cíclico",
  COMR: "Utilidade Pública",
  CPFE: "Utilidade Pública",
  CPLE: "Utilidade Pública",
  CRPG: "Materiais Básicos",
  CRTE: "Bens Industriais",
  CSAN: "Petróleo, Gás e Biocombustíveis",
  CSED: "Consumo Cíclico",
  CSMG: "Utilidade Pública",
  CSNA: "Materiais Básicos",
  CSUD: "Financeiro",
  CTAX: "Bens Industriais",
  CTBA: "Financeiro",
  CTCA: "Consumo não Cíclico",
  CTKA: "Consumo Cíclico",
  CTNM: "Consumo Cíclico",
  CTSA: "Consumo Cíclico",
  CURY: "Consumo Cíclico",
  CVCB: "Consumo Cíclico",
  CXSE: "Financeiro",
  CYRE: "Consumo Cíclico",
  DASA: "Saúde",
  DESK: "Comunicações",
  DEXP: "Materiais Básicos",
  DIRR: "Consumo Cíclico",
  DMVF: "Saúde",
  DOHL: "Consumo Cíclico",
  DOTZ: "Consumo Cíclico",
  DTCY: "Bens Industriais",
  DXCO: "Materiais Básicos",
  EALT: "Bens Industriais",
  ECOR: "Bens Industriais",
  EGGY: "Consumo não Cíclico",
  EGIE: "Utilidade Pública",
  EKTR: "Utilidade Pública",
  EMAE: "Utilidade Pública",
  EMBJ: "Bens Industriais",
  ENEV: "Utilidade Pública",
  ENGI: "Utilidade Pública",
  ENJU: "Tecnologia da Informação",
  ENMT: "Utilidade Pública",
  EPAR: "Financeiro",
  EQMA: "Utilidade Pública",
  EQPA: "Utilidade Pública",
  EQTL: "Utilidade Pública",
  ESPA: "Consumo não Cíclico",
  ESTR: "Consumo Cíclico",
  ETER: "Bens Industriais",
  EUCA: "Materiais Básicos",
  EUFA: "Saúde",
  EVEN: "Consumo Cíclico",
  EZTC: "Consumo Cíclico",
  FESA: "Materiais Básicos",
  FHER: "Materiais Básicos",
  FICT: "Consumo não Cíclico",
  FIEI: "Consumo Cíclico",
  FIGE: "Financeiro",
  FIQE: "Comunicações",
  FLRY: "Saúde",
  FRAS: "Bens Industriais",
  FRIO: "Bens Industriais",
  GEPA: "Utilidade Pública",
  GFSA: "Consumo Cíclico",
  GGBR: "Materiais Básicos",
  GGPS: "Bens Industriais",
  GMAT: "Consumo não Cíclico",
  GOAU: "Materiais Básicos",
  GOLL: "Bens Industriais",
  GPAR: "Utilidade Pública",
  GRND: "Consumo Cíclico",
  GSHP: "Financeiro",
  GUAR: "Consumo Cíclico",
  HAGA: "Materiais Básicos",
  HAPV: "Saúde",
  HBOR: "Consumo Cíclico",
  HBRE: "Financeiro",
  HBSA: "Bens Industriais",
  HBTS: "Financeiro",
  HETA: "Consumo Cíclico",
  HMOB: "Bens Industriais",
  HOOT: "Consumo Cíclico",
  HYPE: "Saúde",
  IFCM: "Tecnologia da Informação",
  IGSN: "Utilidade Pública",
  IGTI: "Financeiro",
  INBR: "Financeiro",
  INEP: "Bens Industriais",
  INNC: "Consumo Cíclico",
  INTB: "Tecnologia da Informação",
  IRBR: "Financeiro",
  ISAE: "Utilidade Pública",
  ITSA: "Financeiro",
  ITUB: "Financeiro",
  IVPR: "Bens Industriais",
  JALL: "Consumo não Cíclico",
  JBSS: "Consumo não Cíclico",
  JFEN: "Consumo Cíclico",
  JHSF: "Consumo Cíclico",
  JOPA: "Consumo não Cíclico",
  JSLG: "Bens Industriais",
  KEPL: "Bens Industriais",
  KLAS: "Consumo Cíclico",
  KLBN: "Materiais Básicos",
  LAND: "Consumo não Cíclico",
  LAVV: "Consumo Cíclico",
  LEVE: "Consumo Cíclico",
  LIGH: "Utilidade Pública",
  LIGT: "Utilidade Pública",
  LJQQ: "Consumo Cíclico",
  LLBI: "Consumo Cíclico",
  LMED: "Saúde",
  LOGG: "Financeiro",
  LOGN: "Bens Industriais",
  LPSB: "Financeiro",
  LREN: "Consumo Cíclico",
  LTEL: "Materiais Básicos",
  LTLA: "Materiais Básicos",
  LUPA: "Petróleo, Gás e Biocombustíveis",
  LUXM: "Bens Industriais",
  LWSA: "Tecnologia da Informação",
  MAPT: "Outros",
  MATD: "Saúde",
  MBRF: "Consumo não Cíclico",
  MCRJ: "Financeiro",
  MDIA: "Consumo não Cíclico",
  MDNE: "Consumo Cíclico",
  MEAL: "Consumo Cíclico",
  MELK: "Consumo Cíclico",
  MERC: "Financeiro",
  MGEL: "Materiais Básicos",
  MGLU: "Consumo Cíclico",
  MILS: "Bens Industriais",
  MLAS: "Tecnologia da Informação",
  MMAQ: "Bens Industriais",
  MNDL: "Consumo Cíclico",
  MNPR: "Consumo não Cíclico",
  MOAR: "Financeiro",
  MOTV: "Bens Industriais",
  MOVI: "Consumo Cíclico",
  MRSA: "Bens Industriais",
  MRVE: "Consumo Cíclico",
  MSPA: "Materiais Básicos",
  MTRE: "Consumo Cíclico",
  MTSA: "Bens Industriais",
  MULT: "Financeiro",
  MWET: "Bens Industriais",
  MYPK: "Consumo Cíclico",
  NATU: "Consumo não Cíclico",
  NEMO: "Materiais Básicos",
  NEOE: "Utilidade Pública",
  NEXP: "Financeiro",
  NGRD: "Tecnologia da Informação",
  NORD: "Financeiro",
  NUTR: "Materiais Básicos",
  OBTC: "Consumo Cíclico",
  ODER: "Consumo não Cíclico",
  ODPV: "Saúde",
  OFSA: "Saúde",
  OIBR: "Comunicações",
  ONCO: "Saúde",
  OPCT: "Petróleo, Gás e Biocombustíveis",
  OPGM: "Outros",
  OPSE: "Outros",
  OPTS: "Outros",
  ORVR: "Utilidade Pública",
  OSXB: "Petróleo, Gás e Biocombustíveis",
  PASS: "Utilidade Pública",
  PATI: "Materiais Básicos",
  PCAR: "Consumo não Cíclico",
  PDGR: "Consumo Cíclico",
  PDTC: "Tecnologia da Informação",
  PEAB: "Financeiro",
  PETR: "Petróleo, Gás e Biocombustíveis",
  PFRM: "Saúde",
  PGMN: "Saúde",
  PINE: "Financeiro",
  PLAS: "Consumo Cíclico",
  PLPL: "Consumo Cíclico",
  PLSC: "Financeiro",
  PMAM: "Materiais Básicos",
  PMSP: "Financeiro",
  PNVL: "Saúde",
  POMO: "Bens Industriais",
  POSI: "Tecnologia da Informação",
  PPAR: "Outros",
  PPLA: "Financeiro",
  PRIO: "Petróleo, Gás e Biocombustíveis",
  PRMN: "Utilidade Pública",
  PRNR: "Bens Industriais",
  PRPT: "Outros",
  PSSA: "Financeiro",
  PSVM: "Bens Industriais",
  PTBL: "Bens Industriais",
  PTCA: "Bens Industriais",
  PTNT: "Consumo Cíclico",
  QUAL: "Saúde",
  QUSW: "Tecnologia da Informação",
  QVQP: "Outros",
  RADL: "Saúde",
  RAIL: "Bens Industriais",
  RAIZ: "Petróleo, Gás e Biocombustíveis",
  RANI: "Materiais Básicos",
  RAPT: "Bens Industriais",
  RBNS: "Bens Industriais",
  RBRA: "Financeiro",
  RCSL: "Bens Industriais",
  RDOR: "Saúde",
  RECV: "Petróleo, Gás e Biocombustíveis",
  REDE: "Utilidade Pública",
  RENT: "Consumo Cíclico",
  RIOS: "Utilidade Pública",
  RNEW: "Utilidade Pública",
  ROMI: "Bens Industriais",
  RPAD: "Financeiro",
  RPMG: "Petróleo, Gás e Biocombustíveis",
  RSID: "Consumo Cíclico",
  RSUL: "Bens Industriais",
  RVEE: "Consumo Cíclico",
  SALT: "Consumo Cíclico",
  SANB: "Financeiro",
  SAPR: "Utilidade Pública",
  SBFG: "Consumo Cíclico",
  SBSP: "Utilidade Pública",
  SCAR: "Financeiro",
  SEER: "Consumo Cíclico",
  SEQL: "Bens Industriais",
  SGPS: "Consumo Cíclico",
  SHOW: "Consumo Cíclico",
  SHUL: "Bens Industriais",
  SIMH: "Financeiro",
  SLCE: "Consumo não Cíclico",
  SMFT: "Consumo Cíclico",
  SMTO: "Consumo não Cíclico",
  SNSY: "Materiais Básicos",
  SOJA: "Consumo não Cíclico",
  SOND: "Bens Industriais",
  SUZB: "Materiais Básicos",
  SYNE: "Financeiro",
  TAEE: "Utilidade Pública",
  TASA: "Bens Industriais",
  TCSA: "Consumo Cíclico",
  TECN: "Consumo Cíclico",
  TELB: "Comunicações",
  TEND: "Consumo Cíclico",
  TFCO: "Consumo Cíclico",
  TGMA: "Bens Industriais",
  TIMS: "Comunicações",
  TKNO: "Materiais Básicos",
  TOKY: "Consumo Cíclico",
  TOTS: "Tecnologia da Informação",
  TPIS: "Bens Industriais",
  TRAD: "Tecnologia da Informação",
  TRIS: "Consumo Cíclico",
  TTEN: "Consumo não Cíclico",
  TUPY: "Bens Industriais",
  TXRX: "Consumo Cíclico",
  UCAS: "Consumo Cíclico",
  UGPA: "Petróleo, Gás e Biocombustíveis",
  UNIP: "Materiais Básicos",
  USIM: "Materiais Básicos",
  VALE: "Materiais Básicos",
  VAMO: "Consumo Cíclico",
  VBBR: "Petróleo, Gás e Biocombustíveis",
  VITT: "Materiais Básicos",
  VIVA: "Consumo Cíclico",
  VIVR: "Consumo Cíclico",
  VIVT: "Comunicações",
  VLID: "Bens Industriais",
  VSPT: "Bens Industriais",
  VSTE: "Consumo Cíclico",
  VTRU: "Consumo Cíclico",
  VULC: "Consumo Cíclico",
  VVEO: "Saúde",
  WDCN: "Tecnologia da Informação",
  WEGE: "Bens Industriais",
  WEST: "Consumo Cíclico",
  WHRL: "Consumo Cíclico",
  WIZC: "Financeiro",
  WLMM: "Bens Industriais",
  YDUQ: "Consumo Cíclico",
};

export function setorDoTicker(ticker: string): string {
  const raiz = ticker.trim().toUpperCase().replace(/\.SA$/, "").replace(/[^A-Z]/g, "").slice(0, 4);
  return SETORES_B3[raiz] ?? "Sem setor";
}
